modLoader="javafml"
license="MIT License"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition/issues"
displayURL="https://github.com/MCTeamPotato/Lost-Cities-Potato-Edition"

credits="McJty"
authors="Team Potato"

[[mods]]
modId="lostcities"
version="${file.jarVersion}"
displayName="LostCities"
description='''
Generate cities all over the world.
'''